### ISSUE TITLE
Support for other OSes.

### ISSUE THREAD

**Issue by chrisgavin** [chrisgavin/slacktoken#3]
Currently only Linux works. It probably wouldn't be too hard to add Windows and macOS support by updating `_get_slack_configuration_directory()` to return the correct path on those operating systems.

**Comment by sampart** [comment]
Looks like https://github.com/chrisgavin/slacktoken/pull/9 adds MacOS support. However, the path given wasn't present for me. I think `~/Library/Application Support/Slack` would work (it does contain a `Cookies` dir), but I then got a different error (`ImportError: cannot import name 'EXACT_TOKEN_TYPES' from 'token' (/usr/local/lib/python3.9/site-packages/slacktoken/token.py)`), so I'm not sure.

**Comment by rneatherway** [comment]
Yes, I'm not sure what is different about Nick's machine, but my Mac has the cookies at `~/Library/Application Support/Slack` like you.

Unfortunately they started encrypting the cookie and that decryption is also platform-specific, so MacOS still isn't supported.

**Comment by chrisgavin** [comment]
#24 should hopefully both handle the different data location on macOS and add support for encrypted cookies.

I've been using an Actions worker to test it, so let me know if you find it doesn't work; a regular user's machine might not be set up in the same way.
